#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/crg-scoreboard ]; then
  rm -f /usr/doc/crg-scoreboard
fi
# End automatically added section
/etc/init.d/crg-scoreboard stop
insserv -r crg-scoreboard
